parameters:
  osVersions: []
  osDetails: []

jobs:
- ${{each os, osdetails in parameters.osVersions, parameters.osDetails}}:
  - job: createAllNew${{os}}
    variables:
      scenario: v2-allNew
      testcase: $(scenario)-$(Build.BuildId)
    steps:
    - script: 'echo ${{osdetails}}'
    - template: update-place-holder.yaml
      parameters:
        scenario: $(scenario)
        testCaseName: $(testcase)
        placeHolder: var-rg-name
        value: $(testcase)
    - template: terraform-deployment-steps.yaml
      parameters:
        testCaseName: $(testcase)
    - template: ansible-deployment-steps.yaml
      parameters:
        testCaseName: $(testcase)
    displayName: 'job ${{p}}'
