parameters:
  osList: []
  a: [
            { "id": 1, "a": "avalue1"},
            { "id": 2, "a": "avalue2"},
            { "id": 3, "a": "avalue3"}
      ]

jobs:
- ${{ each id in parameters.a.*.id }}:
  - job: ${{id}}
    displayName: ${{a.*.a}}
