parameters:
  param: []

jobs:
- ${{each p in parameters.param}}:
  - job: 
    variables:
      scenario: v2-allNew
      testcase: $(scenario)-$(Build.BuildId)
    steps:
    - script: echo p.os_version
    - template: update-place-holder.yaml
      parameters:
        scenario: $(scenario)
        testCaseName: $(testcase)
        placeHolder: var-rg-name
        value: $(testcase)
    - template: terraform-deployment-steps.yaml
      parameters:
        testCaseName: $(testcase)
    - template: ansible-deployment-steps.yaml
      parameters:
        testCaseName: $(testcase)
    displayName: 'job ${{p}}'
