parameters:
  osList: []
  a: [
            { "id": 1, "a": "avalue1"},
            { "id": 2, "a": "avalue2"},
            { "id": 3, "a": "avalue3"}
          ]

jobs:
- ${{ each os in parameters.osList }}:
  - job: createAllNew
    variables:
      scenario: v2-allNew
      testcase: $(scenario)-$(Build.BuildId)
    steps:
    - script: |
        echo $(a.*.id)
    - template: update-place-holder.yaml
      parameters:
        scenario: $(scenario)
        testCaseName: $(testcase)
        placeHolder: var-rg-name
        value: $(testcase)
    - template: terraform-deployment-steps.yaml
      parameters:
        testCaseName: $(testcase)
    - template: ansible-deployment-steps.yaml
      parameters:
        testCaseName: $(testcase)
    displayName: 'job ${{os}}'
